#!/bin/bash
# Example commands for using the networking tracker
# This file is for reference - copy and paste commands you need

echo "🚀 Networking Tracker - Example Commands"
echo "========================================"
echo ""

echo "📋 ADDING COMPANIES"
echo "-------------------"
echo "python add_company.py 'Stripe' --tracker fintech"
echo "python add_company.py 'Square' --tracker fintech"
echo "python add_company.py 'Plaid' --tracker fintech"
echo "python add_company.py 'Oscar Health' --tracker healthtech"
echo "python add_company.py 'Ro' --tracker healthtech"
echo ""

echo "🔍 RESEARCHING CONTACTS"
echo "----------------------"
echo "python find_contacts.py 'Stripe' --tracker fintech"
echo "python find_contacts.py --all --tracker fintech"
echo "python find_contacts.py --all --tracker healthtech"
echo ""

echo "📝 ADDING CONTACT INFORMATION"
echo "----------------------------"
echo "python update_status.py 'Stripe' --tracker fintech \\"
echo "  --contact 'Jane Doe' \\"
echo "  --title 'Senior UX Designer' \\"
echo "  --email 'jane@stripe.com'"
echo ""

echo "python update_status.py 'Square' --tracker fintech \\"
echo "  --website 'https://squareup.com' \\"
echo "  --linkedin 'https://linkedin.com/company/square'"
echo ""

echo "📊 UPDATING STATUS"
echo "-----------------"
echo "python update_status.py 'Stripe' --tracker fintech --status 'Researched'"
echo "python update_status.py 'Stripe' --tracker fintech --status 'Reached Out'"
echo "python update_status.py 'Stripe' --tracker fintech --status 'Responded'"
echo "python update_status.py 'Stripe' --tracker fintech --status 'Meeting Scheduled'"
echo ""

echo "📝 ADDING NOTES"
echo "--------------"
echo "python update_status.py 'Stripe' --tracker fintech \\"
echo "  --notes 'Sent LinkedIn InMail on 1/10/2026'"
echo ""
echo "python update_status.py 'Stripe' --tracker fintech \\"
echo "  --notes 'Great conversation, scheduling coffee chat for next week'"
echo ""

echo "👀 VIEWING INFORMATION"
echo "---------------------"
echo "python update_status.py 'Stripe' --tracker fintech --show"
echo ""

echo "🔧 CHECKING SETUP"
echo "----------------"
echo "python setup_check.py"
echo ""

echo "💡 COMPLETE WORKFLOW EXAMPLE"
echo "---------------------------"
echo "# 1. Add a company"
echo "python add_company.py 'Stripe' --tracker fintech"
echo ""
echo "# 2. Research contacts"
echo "python find_contacts.py 'Stripe' --tracker fintech"
echo "# (Go to LinkedIn and find contacts manually)"
echo ""
echo "# 3. Add contact you found"
echo "python update_status.py 'Stripe' --tracker fintech \\"
echo "  --contact 'Jane Doe' \\"
echo "  --title 'Senior UX Designer' \\"
echo "  --email 'jane@stripe.com' \\"
echo "  --status 'Researched'"
echo ""
echo "# 4. After reaching out"
echo "python update_status.py 'Stripe' --tracker fintech \\"
echo "  --status 'Reached Out' \\"
echo "  --notes 'Sent LinkedIn message on 1/10'"
echo ""
echo "# 5. After they respond"
echo "python update_status.py 'Stripe' --tracker fintech \\"
echo "  --status 'Responded' \\"
echo "  --notes 'Positive response, scheduling call'"
echo ""
echo "# 6. Check current status"
echo "python update_status.py 'Stripe' --tracker fintech --show"
